services:
  db:
    image: postgis/postgis:15-3.3 # Postgres 15 con PostGIS 3.3
    container_name: postgres_leadchain
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: leadchain
    ports:
      - "5432:5432"
    # volumes:
      # PostgreSQL ejecuta automáticamente los .sql en /docker-entrypoint-initdb.d/
      # - ./init-db/db-leadchain.sql:/docker-entrypoint-initdb.d/db-leadchain.sql
      # - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
